In [13]:
import pandas as pd
from nltk.sentiment import SentimentIntensityAnalyzer
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import nltk

In [22]:
nltk.download('vader_lexicon')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package vader_lexicon to C:\Users\EFRAIN
[nltk_data]     LINARES\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\EFRAIN
[nltk_data]     LINARES\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\EFRAIN
[nltk_data]     LINARES\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\EFRAIN
[nltk_data]     LINARES\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [15]:
Data = pd.read_parquet(r'C:\Users/EFRAIN LINARES\Desktop/Henry PI 1\PI MLOps - STEAM/PARQUET\df_review_clean.parquet')

In [16]:
Data

,user_id,user_url,posted,item_id,recommend,review
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted November 5, 2011.",1250,True,Simple yet with great replayability. In my opi...
1,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted July 15, 2011.",22200,True,It's unique and worth a playthrough.
2,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted April 21, 2011.",43110,True,Great atmosphere. The gunplay can be a bit chu...
3,js41637,http://steamcommunity.com/id/js41637,"Posted June 24, 2014.",251610,True,I know what you think when you see this title ...
4,js41637,http://steamcommunity.com/id/js41637,"Posted September 8, 2013.",227300,True,For a simple (it's actually not all that simpl...
...,...,...,...,...,...,...
59328,76561198312638244,http://steamcommunity.com/profiles/76561198312...,Posted July 10.,70,True,a must have classic from steam definitely wort...
59329,76561198312638244,http://steamcommunity.com/profiles/76561198312...,Posted July 8.,362890,True,this game is a perfect remake of the original ...
59330,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 3.,273110,True,had so much fun plaing this and collecting res...
59331,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 20.,730,True,:D
59332,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 2.,440,True,so much fun :D

In [17]:
df_copy = Data.copy()

In [18]:
df_copy['review'] = df_copy['review'].replace(['10/10', '100/100'], 'excelent', regex=True)


df_copy['review'] = df_copy['review'].astype(str)

In [19]:
sid = SentimentIntensityAnalyzer()


stemmer = PorterStemmer()

lemmatizer = WordNetLemmatizer()

In [23]:
def stemming_apply (texto):
    palabras = word_tokenize(texto)
    stemmed_palabras = [stemmer.stem(word) for word in palabras]
    return ' '.join(stemmed_palabras)



df_copy['review'] = df_copy['review'].apply(stemming_apply)

In [24]:
def lematinazion_appy (texto):
    palabras = word_tokenize(texto)
    stemmed_palabras = [stemmer.stem(word) for word in palabras]
    return ' '.join(stemmed_palabras)



df_copy['review'] = df_copy['review'].apply(le)

In [ ]:
def analisis_sentiment (texto, recomend):
    if pd.isnull(texto):
        return 1
    escala_sentiment = sid.polarity_scores(texto)['compound']
    if recomend:
        escala_sentiment += 0.5
    else:
        escala_sentiment -= 0.5
    if escala_sentiment <= -0.05:
        return 0
    elif escala_sentiment >= 0.05:
        return 2
    else:
        return 1


df_copy['sentiment_analisys'] = df_copy.apply(lambda row: analisis_sentiment(row['review'], row['recommend']), axis=1)

df_copy    
df_copy.drop(columns=['review'], inplace=True)

In [31]:
df_copy

,user_id,user_url,posted,item_id,recommend,sentiment_analisys
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted November 5, 2011.",1250,True,2
1,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted July 15, 2011.",22200,True,2
2,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted April 21, 2011.",43110,True,2
3,js41637,http://steamcommunity.com/id/js41637,"Posted June 24, 2014.",251610,True,2
4,js41637,http://steamcommunity.com/id/js41637,"Posted September 8, 2013.",227300,True,2
...,...,...,...,...,...,...
59328,76561198312638244,http://steamcommunity.com/profiles/76561198312...,Posted July 10.,70,True,2
59329,76561198312638244,http://steamcommunity.com/profiles/76561198312...,Posted July 8.,362890,True,2
59330,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 3.,273110,True,2
59331,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 20.,730,True,2
59332,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 2.,440,True,2

In [33]:
positivo_nega = df_copy[(df_copy['sentiment_analisys'] == 2) & (df_copy['recommend'] == False)]

negativo_posi = df_copy[(df_copy['sentiment_analisys'] == 0) & (df_copy['recommend'] == True)]

count_positivos = len(positivo_nega)

count_negativos = len(negativo_posi)

print(f"El conteo de sentimiento negativo pero con recomendacion positiva son: {count_negativos}")

print(f"El conteo de sentimiento positivo pero con recomendacion negativa son: {count_positivos}")

El conteo de sentimiento negativo pero con recomendacion positiva son: 2904
El conteo de sentimiento positivo pero con recomendacion negativa son: 1323

In [34]:
total_conteos = 2904 + 1323

datos_totales = 59333

porcentaje = (total_conteos/datos_totales) * 100

print(f"El porcentaje de errores son de {porcentaje}")

El porcentaje de errores son de 7.124197326951275

In [35]:
df_copy

,user_id,user_url,posted,item_id,recommend,sentiment_analisys
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted November 5, 2011.",1250,True,2
1,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted July 15, 2011.",22200,True,2
2,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"Posted April 21, 2011.",43110,True,2
3,js41637,http://steamcommunity.com/id/js41637,"Posted June 24, 2014.",251610,True,2
4,js41637,http://steamcommunity.com/id/js41637,"Posted September 8, 2013.",227300,True,2
...,...,...,...,...,...,...
59328,76561198312638244,http://steamcommunity.com/profiles/76561198312...,Posted July 10.,70,True,2
59329,76561198312638244,http://steamcommunity.com/profiles/76561198312...,Posted July 8.,362890,True,2
59330,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 3.,273110,True,2
59331,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 20.,730,True,2
59332,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,Posted July 2.,440,True,2

In [36]:
df_copy.to_parquet(r'C:\Users\EFRAIN LINARES\Desktop\Henry PI 1\PI MLOps - STEAM\PARQUET\analisis_sentiment.parquet', index= False)